"""Add subcategorie table and link to abonnement

Revision ID: 50bca1936872
Revises: 66b7f1952064
Create Date: 2025-01-19 15:44:06.658007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bca1936872'
down_revision = '66b7f1952064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategorie_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.alter_column(
            'url',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=200),
            nullable=False
        )
        batch_op.alter_column(
            'contractduur',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=20),
            existing_nullable=True
        )
        batch_op.alter_column(
            'aanbiedingen',
            existing_type=sa.VARCHAR(length=255),
            type_=sa.String(length=200),
            existing_nullable=True
        )
        batch_op.create_foreign_key(
            'fk_abonnement_subcategorie',
            'subcategorie',
            ['subcategorie_id'],
            ['id']
        )
        batch_op.drop_column('categorie_id')

    # Verwijder de server default na migratie
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.alter_column('subcategorie_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_abonnement_subcategorie', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_abonnement_categorie',
            'categorie',
            ['categorie_id'],
            ['id']
        )
        batch_op.alter_column(
            'aanbiedingen',
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True
        )
        batch_op.alter_column(
            'contractduur',
            existing_type=sa.String(length=20),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True
        )
        batch_op.alter_column(
            'url',
            existing_type=sa.String(length=200),
            type_=sa.VARCHAR(length=255),
            nullable=True
        )
        batch_op.drop_column('subcategorie_id')
    # ### end Alembic commands ###
