"""Add slug field to Abonnement

Revision ID: 5ca5d39519f2
Revises: caa04d06aedf
Create Date: 2025-04-19 21:18:01.370158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca5d39519f2'
down_revision = 'caa04d06aedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_logs')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('naam',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('naam',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))

    op.create_table('chatbot_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('vraag', sa.TEXT(), nullable=False),
    sa.Column('antwoord', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
