"""Add slug column (nullable)

Revision ID: 661340aa6e9b
Revises: 5ca5d39519f2
Create Date: 2025-04-20 13:31:38.525246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661340aa6e9b'
down_revision = '5ca5d39519f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_abonnement')
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_abonnement_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.drop_constraint('uq_abonnement_slug', type_='unique')
        batch_op.drop_column('slug')

    op.create_table('_alembic_tmp_abonnement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.VARCHAR(length=100), nullable=False),
    sa.Column('beschrijving', sa.VARCHAR(length=140), nullable=True),
    sa.Column('filter_optie', sa.VARCHAR(length=20), nullable=False),
    sa.Column('logo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('prijs', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contractduur', sa.VARCHAR(length=20), nullable=True),
    sa.Column('aanbiedingen', sa.VARCHAR(length=200), nullable=True),
    sa.Column('annuleringsvoorwaarden', sa.TEXT(), nullable=True),
    sa.Column('voordelen', sa.TEXT(), nullable=True),
    sa.Column('beoordelingen', sa.FLOAT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('subcategorie_id', sa.INTEGER(), nullable=False),
    sa.Column('volgorde', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('frequentie_bezorging', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prijs_vanaf', sa.FLOAT(), nullable=True),
    sa.Column('prijs_tot', sa.FLOAT(), nullable=True),
    sa.Column('wat_is_het_abonnement', sa.TEXT(), nullable=True),
    sa.Column('waarom_kiezen', sa.TEXT(), nullable=True),
    sa.Column('hoe_werkt_het', sa.TEXT(), nullable=True),
    sa.Column('past_dit_bij_jou', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['subcategorie_id'], ['subcategorie.id'], name='fk_abonnement_subcategorie'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_abonnement_slug')
    )
    # ### end Alembic commands ###
