"""Kolom datum toegevoegd

Revision ID: 66b7f1952064
Revises: 
Create Date: 2025-01-18 19:21:55.251597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b7f1952064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_bericht', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_bericht', schema=None) as batch_op:
        batch_op.drop_column('datum')

    # ### end Alembic commands ###
