"""Voeg beschrijving toe aan subcategorie

Revision ID: 15d0c90a25ef
Revises: bab429582732
Create Date: 2025-07-30 21:49:31.793666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d0c90a25ef'
down_revision = 'bab429582732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschrijving', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategorie', schema=None) as batch_op:
        batch_op.drop_column('beschrijving')

    # ### end Alembic commands ###
