"""Add volgorde to Abonnement

Revision ID: 3c9f10954c78
Revises: 9c9586389d3f
Create Date: 2025-01-28 19:40:01.726555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9f10954c78'
down_revision = '9c9586389d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volgorde', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.drop_column('volgorde')

    # ### end Alembic commands ###
