"""Add volgorde column to Categorie

Revision ID: 9c9586389d3f
Revises: 50bca1936872
Create Date: 2025-01-27 21:46:14.411965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9586389d3f'
down_revision = '50bca1936872'
branch_labels = None
depends_on = None


def upgrade():
    # Voeg de nieuwe kolom 'volgorde' toe met een standaardwaarde
    with op.batch_alter_table('categorie') as batch_op:
        batch_op.add_column(sa.Column('volgorde', sa.Integer(), nullable=False, server_default='0'))
    
    # Verwijder de server_default na het updaten van bestaande rijen
    with op.batch_alter_table('categorie') as batch_op:
        batch_op.alter_column('volgorde', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_column('volgorde')

    # ### end Alembic commands ###
