"""blogpost m2m taxonomie

Revision ID: 393aefabfc51
Revises: 42818f5508c1
Create Date: 2025-10-23 21:23:02.309891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393aefabfc51'
down_revision = '42818f5508c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))

    # ### end Alembic commands ###
