"""Add affiliate_url to Abonnement

Revision ID: 42818f5508c1
Revises: 94bf4367411b
Create Date: 2025-08-17 11:39:37.947885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42818f5508c1'
down_revision = '94bf4367411b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.drop_column('affiliate_url')

    # ### end Alembic commands ###
