"""add youtube_url to abonnement and create abonnement_foto table

Revision ID: 94bf4367411b
Revises: 15d0c90a25ef
Create Date: 2025-08-06 19:40:12.601594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bf4367411b'
down_revision = '15d0c90a25ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.drop_column('youtube_url')

    # ### end Alembic commands ###
