"""Voeg beschrijving toe aan categorie

Revision ID: bab429582732
Revises: f814ef94a6cf
Create Date: 2025-07-27 21:44:33.735976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab429582732'
down_revision = 'f814ef94a6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschrijving', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_column('beschrijving')

    # ### end Alembic commands ###
