"""Add bedrijf_id column to Abonnement

Revision ID: f814ef94a6cf
Revises: 3f5a1adfe640
Create Date: 2025-06-19 22:16:02.766843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f814ef94a6cf'
down_revision = '3f5a1adfe640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrijf_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_abonnement_bedrijf_id',   # expliciete naam voor de FK
            'bedrijf',
            ['bedrijf_id'],
            ['id']
        )

    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(
            'uq_categorie_slug',         # naam voor de unique constraint
            ['slug']
        )

    with op.batch_alter_table('subcategorie', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(
            'uq_subcategorie_slug',      # naam voor de unique constraint
            ['slug']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategorie', schema=None) as batch_op:
        batch_op.drop_constraint('uq_subcategorie_slug', type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categorie_slug', type_='unique')
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('abonnement', schema=None) as batch_op:
        batch_op.drop_constraint('fk_abonnement_bedrijf_id', type_='foreignkey')
        batch_op.drop_column('bedrijf_id')
    # ### end Alembic commands ###
